export { ClientDetail } from './ClientDetail'
export { ClientHome } from './ClientHome'
export { ClientInsert } from './ClientInsert'
export { ClientList } from './ClientList'
export { ClientUpdate } from './ClientUpdate'
